In [ ]:
!pip install statsmodels seaborn scipy matplotlib pandas numpy scikit-learn patsy pyarrow openpyxl requests sqlalchemy

/bin/bash: /usr/local/bin/pip: /usr/local/opt/python/bin/python3.7: bad interpreter: No such file or directory


In [1]:
!git clone https://github.com/wesm/pydata-book.git

Cloning into 'pydata-book'...
remote: Enumerating objects: 553, done.
remote: Counting objects: 100% (28/28), done.
remote: Compressing objects: 100% (25/25), done.
remote: Total 553 (delta 23), reused 3 (delta 3), pack-reused 525 (from 1)
Receiving objects: 100% (553/553), 63.76 MiB | 1.19 MiB/s, done.
Resolving deltas: 100% (209/209), done.
Updating files: 100% (208/208), done.


In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels as sm

In [1]:
import itertools

def first_letter(x):
    return x[0]

names = ['Alice', 'Adam' 'Bob', 'Charlie', 'David', 'Eve']

for letter, names in itertools.groupby(sorted(names, key=first_letter), key=first_letter):
    print(letter, list(names))

A ['Alice', 'AdamBob']
C ['Charlie']
D ['David']
E ['Eve']


# Numpy 

In [9]:
# Numpy faster mathematical opertions than python lists

# easiest way to create a numpy array is to use the np.array function
data = np.array([[1.5, 2.5, 3.5, 4.5], [0, 1, 2, 3]])
print(data)

data = data * 10 
print(data)

# each array has shape and dtype attributes
print("deminsions of the array", data.ndim)
print("shape of numpy array", data.shape)
print("data type of the array",data.dtype)

#easy to create a numpy array with zeros
data = np.zeros((2, 3))
print(data)
# or with ones
data = np.ones((2, 3))
print(data)

#array-valued operations
print("using arange function:",np.arange(10))  # creates an array with values from 0 to 9
print(np.arange(0, 10, 2))  # creates an array with values from 0 to 8 with a step of 2

arr = np.array([1,2,3,4,5])
print(arr.dtype)
float_arr = arr.astype(np.float64)  # convert to float
print(float_arr.dtype)


[[1.5 2.5 3.5 4.5]
 [0.  1.  2.  3. ]]
[[15. 25. 35. 45.]
 [ 0. 10. 20. 30.]]
deminsions of the array 2
shape of numpy array (2, 4)
data type of the array float64
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
using arange function: [0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
int64
float64
